apiVersion: v1
kind: Service
metadata:
  name: huey-service
spec:
  type: LoadBalancer
  selector:
    app: huey
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080