name: Publish Docs

on:
  push:
    branches:
      - "master"

jobs:
  publish_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make generate_docs
      - uses: jakejarvis/s3-sync-action@master
        with:
          # args: --acl public-read --follow-symlinks --delete
          args: --follow-symlinks --delete
        env:
          # upload to http://docs.rubikloudcorp.com/rubicore/
          AWS_S3_BUCKET: ${{ secrets.DOCS_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "html" # optional: defaults to entire repository
          DEST_DIR: "rubicore"
