name: Unit Tests

on:
  pull_request:
    branches:
      - "master"

jobs:
  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Prepare java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen

      - name: Run unit tests
        run: lein test
